# Adapted from https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml

name: Build Wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: cp*
          CIBW_SKIP: "*-win32 *_i686 *musllinux*"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests/test_chatglm_cpp.py

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
